export { default as AddQuestionSvg } from './svg/add.svg';
export { default as DeleteQuestionSvg } from './svg/delete.svg';
export { default as ExcelSvg } from './svg/excel.svg';
export { default as ImportQuestionSvg } from './svg/import.svg';
export { default as imgEncuesta } from './icons/encuesta.png';
export { default as userImg } from './icons/user.png';
export { default as imgNuevaEncuesta } from './icons/Icon.png';
export { default as Logo } from './logos/Logo.png';
export { default as Logo2 } from './logos/LogoAgro360-2.png'
export { default as LogoBlanco } from './logos/LogoAgro360Blanco.png';
export { default as LogoSenaBlanco } from './logos/logo-sena-blanco.png';